### ISSUE TITLE
Does the script consider disabled songs on spotify? 

### ISSUE THREAD

**Issue by KeenMaron** [rnagabhyrava/plex-playlist-sync#63]
Hi,

Sometimes songs on Spotify have become disabled after a while, but you can still see them in playlists, grayed out. If I have these songs locally, the user might forget that they even exist in the local library and just using the playlists.

So, does the script take into consideration the disabled songs on Spotify and add them to the Plex playlist if they are still available locally?

**Comment by rnagabhyrava** [comment]
If I am remembering this correctly, the disabled songs show up as a malformed name in the API response and so cannot be searched and added to the local playlist. I may be wrong on this, you can give it a try and post your findings here.

**Comment by KeenMaron** [comment]
I've just created a playlist with 10 disabled Spotify tracks that are locally available. The script works; it still finds the songs and creates a playlist. However, I'm confused because some playlists are missing several songs, and it's quite challenging to determine why and which songs are missing. Plex and Plexamp lack many features, such as searching playlists, and the UX is really bad in some points :D

**Comment by rnagabhyrava** [comment]
> Why songs are missing?

Because the songs are not found in local. This could be because the song doesn't exist or didn't match. The script searches by song title along with Artist name and _then_ the album name. For a song to match it should at least have same track name and similar artist name.

> Which songs are missing?

There is a flag in the compose file that you can turn on to write the missing songs per playlist as a csv file.

**Comment by KeenMaron** [comment]
ok i will try to figure out why the songs are missing in the playlist, i'm sure some songs are present but not added to the playlist
